; -*- mode: mr32asm; tab-width: 4; indent-tabs-mode: nil; -*-
; ----------------------------------------------------------------------------
; Machine configuration definitions.
; ----------------------------------------------------------------------------

ROM_START     = 0x00000000

RAM_START     = 0x40000000
RAM_SIZE      = 256*1024

ERAM_START    = 0x80000000
ERAM_SIZE     = 0

MMIO_START    = 0xc0000000

